/*
Help file for MDM installation with oracle database.
**all the passwords should be the same as userID with lowercase**
1. Create user
2 create database 
3.create the tablespaces. 
4. 
*/


Create user MDMAdmin identified by mdmadmin;

--providing roles 
grant connect to mdmadmin;
grant connect,resource,dba to mdmadmin;


--providing privis 


--creating the tables space as per the instructions provided in the guide.
--here am using the local path of my computer.Please makesure to change.

create BIGFILE TABLESPACE CMX_DATA NOLOGGING DATAFILE 
'D:\#MDM DATABASE FILES/CMX_DATA1.dbf' SIZE 2048M REUSE EXTENT
    MANAGEMENT LOCAL
    
--Creating the index files. 

CREATE BIGFILE TABLESPACE CMX_INDX NOLOGGING DATAFILE 
'D:\#MDM DATABASE FILES/CMX_INDX1.dbf' 
 SIZE 2048M REUSE EXTENT MANAGEMENT LOCAL;  
 
 
 --creating the temp space
 
 
CREATE BIGFILE TABLESPACE CMX_temp NOLOGGING DATAFILE 
'D:\#MDM DATABASE FILES/CMX_TEMP1.dbf' 
 SIZE 2048M REUSE EXTENT MANAGEMENT LOCAL ; 
 
--new tables space for BPM DATA 


CREATE BIGFILE TABLESPACE BPM_DATA NOLOGGING DATAFILE 
'D:\#MDM DATABASE FILES/BPM_DATA1.dbf' 
 SIZE 2048M REUSE EXTENT MANAGEMENT LOCAL
 
 
 /*
 -- Setting up the previleges to the users
 -- database user should have
 1. DBMS_LOCK
 
 */
 
 
GRANT SELECT ON SYS.PENDING_TRANS$ to mdmadmin with grant option;

GRANT SELECT ON SYS.DBA_PENDING_TRANSACTIONS TO mdmadmin with grant option; 

GRANT  SELECT ON SYS.DBA_2PC_PENDING TO MDMADMIN WITH GRANT OPTION;

GRANT EXECUTE ON SYS.DBMS_XA TO MDMADMIN WITH GRANT OPTION;

GRANT EXECUTE ON SYS.DBMS_LOCK TO MDMADMIN WITH GRANT OPTION;

--OTHER GRANTS 

GRANT  SELECT ON ALL_CONSTRAINTS TO mdmadmin WITH GRANT OPTION ;
GRANT  SELECT ON ALL_CONS_COLUMNS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON ALL_DIRECTORIES TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON ALL_INDEXES TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON ALL_IND_COLUMNS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON ALL_JOBS  TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON ALL_TABLES TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON ALL_TAB_COLUMNS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON ALL_VIEWS TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON DBMS_APPLICATION_INFO TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON DBMS_JOB TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON DBMS_OUTPUT TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON DBMS_STANDARD TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON DBMS_SQL TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON DBMS_STATS TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON DBMS_UTILITY TO mdmadmin WITH GRANT OPTION;

GRANT  EXECUTE ON PLITBLM TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON STANDARD TO mdmadmin WITH GRANT OPTION;
GRANT  EXECUTE ON SYS_STUB_FOR_PURITY_ANALYSIS TO mdmadmin WITH GRANT OPTION;

GRANT  SELECT ON USER_CONSTRAINTS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_CONS_COLUMNS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_EXTERNAL_TABLES TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_INDEXES TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_JAVA_POLICY TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_OBJECTS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_SEQUENCES TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_SOURCE TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_TABLES TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_TAB_COLS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_TAB_COLUMNS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON USER_TRIGGERS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON UTL_FILE TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON V$NLS_PARAMETERS TO mdmadmin WITH GRANT OPTION;
GRANT  SELECT ON V$VERSION TO mdmadmin WITH GRANT OPTION;




